name: Zhou2020
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bedops=2.4.35
  - bedtools=2.23.0
  - bioconductor-genomicranges=1.26.4
  - pybedtools=0.7.10
  - python=3.6.6
  - r=3.3.2
  - r-argparse=1.0.4
  - r-base=3.3.2
  - r-base64enc=0.1_3
  - r-data.table=1.10.4
  - r-dplyr=0.7.4
  - r-ggplot2=2.2.0
  - r-ggpubr=0.1.6
  - r-ggrepel=0.6.5
  - r-ggsci=2.7
  - r-ggsignif=0.4.0
  - r-gplots=3.0.1
  - r-gridextra=2.2.1
  - r-gtools=3.5.0
  - r-psych=1.6.9
  - r-stringr=1.1.0
  - snakemake=4.0.0
